import { EventEmitter } from "@angular/core";
import { ControlValueAccessor } from "@angular/forms";
import { GWSelect, SelectModal } from "../utils/select.modal";
import { GWControl } from "../utils/gw-control";
import { GWPopoverDirective } from "../popover/popover.directive";
export declare const GW_SINGLE_SELECT_VALUE_ACCESSOR: any;
export declare class GWSingleSelectComponent extends GWControl implements ControlValueAccessor {
    onSave: EventEmitter<any>;
    onDataselect: EventEmitter<any>;
    popover: GWPopoverDirective;
    _filter: string;
    data: GWSelect[];
    value: string | SelectModal;
    selectLabel: string;
    _select_modal: string;
    _select_value: GWSelect;
    _single_select_value: GWSelect;
    onChange: any;
    onTouched: any;
    _data: any[];
    clear(): void;
    updateNgModel(): void;
    save(): void;
    cancel(): void;
    remove(): void;
    onSelect(item: any): void;
    writeValue(val: string | SelectModal): void;
    refreshUI(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
}
