import { EventEmitter } from "@angular/core";
import { ControlValueAccessor } from "@angular/forms";
import { GWSelect, MultiSelectModal } from "../utils/select.modal";
import { GWControl } from "../utils/gw-control";
import { GWPopoverDirective } from "../popover/popover.directive";
export declare const GW_SELECT_VALUE_ACCESSOR: any;
export declare class GWMultiSelectComponent extends GWControl implements ControlValueAccessor {
    onSave: EventEmitter<any>;
    popover: GWPopoverDirective;
    _filter: string;
    data: GWSelect[];
    values: any[] | MultiSelectModal;
    _val: any[] | MultiSelectModal;
    _select_modal: string;
    _select_value: GWSelect;
    _multi_select_value: any[] | GWSelect[];
    onChange: any;
    onTouched: any;
    readonly labels: string;
    _data: any[];
    clear(): void;
    updateNgModel(): void;
    save(): void;
    cancel(): void;
    remove(): void;
    writeValue(val: any[] | MultiSelectModal): void;
    refreshUI(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
}
